/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.03.04 at 01:18:28 PM CST
//

package com.dell.isg.smi.commons.utilities.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * The Class Pages.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Pages", propOrder = { "current", "previous", "next", "total" })
public class Pages {

    protected long current;
    protected long previous;
    protected long next;
    protected long total;


    /**
     * Gets the value of the current property.
     *
     * @return the current
     */
    public long getCurrent() {
        return current;
    }


    /**
     * Sets the value of the current property.
     *
     * @param value the new current
     */
    public void setCurrent(long value) {
        this.current = value;
    }


    /**
     * Gets the value of the previous property.
     *
     * @return the previous
     */
    public long getPrevious() {
        return previous;
    }


    /**
     * Sets the value of the previous property.
     *
     * @param value the new previous
     */
    public void setPrevious(long value) {
        this.previous = value;
    }


    /**
     * Gets the value of the next property.
     *
     * @return the next
     */
    public long getNext() {
        return next;
    }


    /**
     * Sets the value of the next property.
     *
     * @param value the new next
     */
    public void setNext(long value) {
        this.next = value;
    }


    /**
     * Gets the value of the total property.
     *
     * @return the total
     */
    public long getTotal() {
        return total;
    }


    /**
     * Sets the value of the total property.
     *
     * @param value the new total
     */
    public void setTotal(long value) {
        this.total = value;
    }

}
