/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.03.04 at 01:18:28 PM CST
//

package com.dell.isg.smi.utilities.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * The Class PagedResult.
 *
 * @param <T> the generic type
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "data", "pagination", "pages" })
@XmlRootElement(name = "PagedResult")
public class PagedResult<T> {

    @XmlElement(name = "Data", required = true)
    protected List<T> data;
    @XmlElement(required = true)
    protected Pagination pagination;
    @XmlElement(required = true)
    protected Pages pages;


    /**
     * Gets the value of the data property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the data property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Object }
     *
     * @return the data
     */
    public List<T> getData() {
        if (data == null) {
            data = new ArrayList<T>();
        }
        return this.data;
    }


    /**
     * Gets the value of the pagination property.
     *
     * @return possible object is {@link Pagination }
     *
     */
    public Pagination getPagination() {
        return pagination;
    }


    /**
     * Sets the value of the pagination property.
     *
     * @param value allowed object is {@link Pagination }
     *
     */
    public void setPagination(Pagination value) {
        this.pagination = value;
    }


    /**
     * Gets the value of the pages property.
     *
     * @return possible object is {@link Pages }
     *
     */
    public Pages getPages() {
        return pages;
    }


    /**
     * Sets the value of the pages property.
     *
     * @param value allowed object is {@link Pages }
     *
     */
    public void setPages(Pages value) {
        this.pages = value;
    }

}
